<?php

class Tutorial_L6E01Models_Block_Helloworld extends Mage_Core_Block_Template
{
    /**
     * Here models & collections loaded, data processed.
     * Or in _prepareLayout()
     *
     * @param array $args
     */
    public function __construct(array $args = array())
    {
        parent::__construct($args); // TODO: Change the autogenerated stub
    }

    /**
     * Here models & collections loaded, data processed.
     * Or in a constructor :)
     *
     * @return Mage_Core_Block_Abstract
     */
    protected function _prepareLayout()
    {
        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }

    /**
     * Before rendering html, but after trying to load cache
     *
     * @return Mage_Core_Block_Abstract
     */
    protected function _beforeToHtml()
    {
        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }

    /**
     * Processing block html after rendering
     *
     * @param   string $html
     * @return  string
     */
    protected function _afterToHtml($html)
    {
        return parent::_afterToHtml($html); // TODO: Change the autogenerated stub
    }

    /**
     * Render block HTML
     *
     * @return string
     */
    protected function _toHtml()
    {
        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }


}